### PR TITLE
2016 v7 root files for fake rates

### PR DESCRIPTION
**Pull request by friccita**
Here are the 2016 v7 fake rate root files, following the same directory naming and populating scheme as for 2016 v6 (which means that Ele and Muon root files are found in all WP folders).

For example: Tight_80X and Tight_80X_SS
   - Tight_80X contains fake rates for muon WP Lepton_isTightMuon_cut_Tight80x and electron WP Lepton_isTightElectron_mva_90p_Iso2016
   - Tight_80X_SS contains fake rates for muon WP Lepton_isTightMuon_cut_Tight80x (again) and electron WP Lepton_isTightElectron_mva_90p_Iso2016_SS

### CODE REVIEW

**Comment by uajanssen** [comment]
Hi @friccita 

Can you confirm me what is what because I see muon files in the 4 directories of the electron WP and then electron files in the 2 directories of muon WP.

I would expect:
* 2 directories for muons WP with only muon FR/PR 
* 4 directories for electron WP with only electron FR/PR
Like that there would be no ambiguity wrt which files belong to which WP's

Could you clean a bit before I merge
Thanks

**Comment by friccita** [comment]
@uajanssen I put the muon files in the electron WP directories and electron files in the muon WP directories because I saw that this was the pattern also for the 2016v6 fake rates: https://github.com/latinos/LatinoAnalysis/tree/master/NanoGardener/python/data/fake_prompt_rates/Full2016v6. I probably misunderstood what that was about; I can remove the muon files from the electron folders and vice versa.

**Comment by friccita** [comment]
@uajanssen @cedricpri Sorry for the mess earlier; I have removed the electron files from the muon folders and the muon files from the electron folders, and fixed the organization of the WP folders in general.

**Comment by uajanssen** [comment]
Thanks @friccita. This make sense to me now as I can identify which sets of files correspond to which WP. I am merging and I will configure the fakes for the 2 muon WP and 4 ele WP

**Pull request merged**
