### PR TITLE
Adding new JetPUID SF and uncty module with the most up-to-date input

### PR DESCRIPTION
**Pull request by TomasKello**
Updated JetSFMaker.py to handle the newest source of eff/mistag jet PU ID SF and uncties (stat + syst).
Updated config JetPUID_cfg.py
Added new source PUID_80XTraining_EffSFandUncties.root and removed the old one.

### CODE REVIEW

**Comment by amassiro** [comment]
Ciao! Is this new pu-jetId the latest and greatest from jetmet?
We have been told that this new pu-jetId should fix the discrepancies that we have shown in the jet eta occupancy (the infamous "horns").
If this is the case, it would be great to have this id included in the upcoming production of trees!
And if confirmed we would gain a lot in terms of phase space for VBF and VBS analyses  (in 2017).
@valsdav @amassiro

**Comment by lviliani** [comment]
Hello, as far as I understand in this PR Tomas has updated the latest PU ID scale factors and associated uncertainties, which will be added as new branches starting from v7 production.
But the jet PU ID itself is taken from NanoAODv6 if I am not wrong.

**Comment by TomasKello** [comment]
Hi, yes this is all about Jet PU ID SFs and their stat and syst uncertainties. Syst. uncertainties should be used when calculating efficiency for real jets (matched to gen-jets) to pass PU ID. Similar for calculating mistag rate. However here, PU ID is still considered to be one retrieved from training with 80X so corresponding to nAODv6 (for all 3 years and 3 WPs). As far as I now, newer version of PU ID will come with nAODv7 and it is still under PR review.

**Comment by amassiro** [comment]
Ok, Thanks a lot for the prompt feedback.

**Pull request merged**
