### PR TITLE
Added keep_and_drop branches option

### PR DESCRIPTION
**Pull request by fmanteca**

### CODE REVIEW

**Comment by valsdav** [comment]
Hi Pedro!
This PR will be really useful!
Can I suggest to find a way to use relative path (to the framework folders) for the keep_and_drop file?
Currently it points to your afs folders and I think this can be a problem.

Thanks!
Davide

**Comment by fmanteca** [comment]
Hi Davide, 
sorry, I took some days off. 
Yutaro has already included this option in #58, so I think we can close the request.

Pedro

**Comment by valsdav** [comment]
Hi Pedro, 
ok, thanks anyway!
Davide

**Comment by uajanssen** [comment]
Can I close this ?

**Comment by fmanteca** [comment]
yes, you can

**Pull request closed without merging**
