### PR TITLE
add FatJet Selection for SemiLeptonic channel analysis

### PR DESCRIPTION
**Pull request by soarnsoar**
Hi. I add FatJet Selection module for High mass semileptonic channel analysis .

To make the selection module I refered to JetSel.py's convention. 

I can check that pt/eta/id cut are applied well via fatjetSel in Step.py. I check pt/eta/id distribution in output tree.

For the test, I used the following chain module to run only "fatjetSel"

  'test_jhchoi_fatjet' :  {
                  'isChain'    : True  ,
                  'do4MC'      : True  ,
                  'do4Data'    : False ,
                  'selection'  : '"((nElectron+nMuon)>0)"' ,
                  'subTargets' : ['fatjetSel'],
                },

### CODE REVIEW

**Comment by soarnsoar** [comment]
I added tau21 cut to FatJetSel.py.

After more tests, i will merge the PR.

**Comment by soarnsoar** [comment]
Hi Giulio,

Thanks for reply!

I can see the cuts are applied well but maybe overwriting is not safe in some cases.

Then, should I create a new branch such as "CleanFatJet"?(And collection of selected fatjet as its variable)?


Best,

Junho

**Comment by lenzip** [comment]
The place where it is not safe is cross referencing between collections.
E.g. Electrons have an index to the overlapping jet in the Jet_ 
collection. If we change the Jet collection, that index does not point 
to the right jet anymore.
It may not be the case for FatJets, that they are referenced by index in 
other collections, but better to be safe and stick to not changing the 
original collections.
Giulio

**Comment by soarnsoar** [comment]
Ah, Okay. If another object(electron) is pointing index of the object(jet), it could be dangerous to change index of the object(jet). I agree. Thank you for discussion :)
 I'll update this PR when it's ready.

**Comment by lenzip** [comment]
HI @soarnsoar , is this PR ready to be merged?

**Comment by soarnsoar** [comment]
I want to close this PR. I 'll make another PR after I make a proper one.

**Pull request closed without merging**
