### PR TITLE
Adding JERMaker module:

### PR DESCRIPTION
**Pull request by TomasKello**
- apply JER SF corrections to CleanJet (optionally other jet coll) pT and mass
- using jetSmearer module (central tool) -> unable to propagate SF on PuppiMET for now
- store correcion factors
- store up/down JER variation branches

### CODE REVIEW

**Comment by amassiro** [comment]
Question: should the nominal collection be replaced instead with the nominal smearing and saving the smearing factor?
Otherwise, all kinematic (and MVA) variables that depend on jets pt will not be updated.
This is what we did back in Run I.
What do you think?

**Comment by TomasKello** [comment]
Hi Andrea, so you say I should rather remain CleanJet coll as it is and storing only nominal correction factor? In code = jet_pt_jerNomVal

**Comment by amassiro** [comment]
Maybe I mis-read the code. What I think would be great to obtain:
- cleanedJet collection now has the pt smeared (only MC samples, data is left untouched)
- since the smearing is applied, a pt re-ordering is needed (e.g. previous cleaned jet (0) could be current (1) ... and so on)
- all relevant variables depending on jet pt recalculated
- storing the "smearing factor" in the collection, to be able to remove its effect, to study the effect on simple variables


If this is already what is happening, sorry, I mis-read.

**Comment by TomasKello** [comment]
Your third point might be not implemented in case there are other variables calculated based on CleanJet pt/mass value, indeed. In that case this module must be run before any calculation is done. Alternatively I can explicitly invoke re-calculation of these pt-dependent variables from JERMaker itself. What do you think?

**Comment by amassiro** [comment]
@TomasKello , yes, I was thinking about adding in [1] in order to run the various "lxxxKin" just after that.

Is the pt-re-ranking already performed? Great!

Maybe this very same PR could have also the fix in [1] included.

[1] https://github.com/latinos/LatinoAnalysis/blob/master/NanoGardener/python/framework/Steps_cfg.py

**Comment by uajanssen** [comment]
@TomasKello @amassiro : Is everything fixed now in that module as you agreed ? We might restart v7 and hence include it

**Comment by amassiro** [comment]
I'm not sure if the current implementation is changing the nominal or adding a new branch ... 
It should change the nominal into the JER varied, and keep the nominal or the correction factor somewhere, in my opinion.

**Comment by TomasKello** [comment]
It is overwriting old CleanJet_pt by new CleanJet_pt*smearFactor and storing smear factor as well in case you want to undo smearing.

**Comment by TomasKello** [comment]
And it is creating up/down variations for pT (and mass) as separate branches as well.

**Comment by amassiro** [comment]
perfect!

**Comment by TomasKello** [comment]
Added JERMaker to steps preceding kinematics calculation. Please crosscheck and merge.

**Comment by valsdav** [comment]
Great! Sounds good to me

**Comment by amassiro** [comment]
> @lviliani @amassiro: Can we merge and do we want to include this as default in v7

I think the JER (nominal value) should be included in the nominal, as Tomas was showing, it improves the MC description of the jet multiplicity.

**Pull request merged**
