### PR TITLE
Added QCD enriched samples

### PR DESCRIPTION
**Pull request by fmanteca**
for v5 production (nanoAODv4)

### CODE REVIEW

**Comment by uajanssen** [comment]
Did you also add the x-sections in the other file or where they available already ?

**Comment by uajanssen** [comment]
and BTW once merged ask Lorenzo to produce them, my slots are fully busy with nAODv5

**Comment by fmanteca** [comment]
yes, the xsecs were included by Junho some weeks ago. 
Do not worry about the production, I will do it myself. Thanks

**Comment by uajanssen** [comment]
Be careful that the production might not work with the HEAD
You need an old setup for Full201Xv5

**Pull request merged**
