### PR TITLE
UL JetPUID SF module

### PR DESCRIPTION
**Pull request by TomasKello**
Module will create following branches:
- puidWeight (Up/Down) 
- Jet_PUIDSF_loose (Up/Down)
Former to be applied as per event scaling. Latter is available just in case.
**Pre-requisites**: correctionlib, jsonpog-integration 
Recipe to calculate weights presented here is a subject to your review. Please merge only if cross-checked.

### CODE REVIEW

**Comment by TomasKello** [comment]
Hi @lviliani, I have not changed the procedure w.r.t to previous module used for pre-UL samples. What made you to use different procedure on the fly? Can you point me to it? Current recommendation is the same as before and that is to use "BTagSF"-like approach where MC eff is needed.

**Comment by TomasKello** [comment]
Hi Lorenzo, alias you sent is strictly speaking not correct - issue is that this way you count also with jets from Jet collection not passing lepton cleaning procedure (and we do NOT apply PU ID on those jets) so our suggestion was to use this awkwardly complicated [formula](https://github.com/latinos/PlotsConfigurations/blob/master/Configurations/EFT/ggH/Full2018/nAODv7_Full2018v7/aliases.py#L208). It was however crosschecked by Giulio around that time that difference is minimal so you should not be worried if you didn't use it in Legacy. 
Nevertheless, I wanted to make our life easier with UL module so:
- jets not passing cleaning procedure or jet ID are ignored by setting weight = 1.0
- jets below 30GeV are ignored (we don't use them)
- clean jets over 50GeV are ignored (we do not apply PU ID)
- jets are further treated differently if they pass PU jet ID and if they are matched to Gen collection
Is newly proposed procedure more clear now?

**Comment by lviliani** [comment]
Hi Tomas, yes I understand that.
I was just not sure about using the MC efficiencies for the SFs, given that there are also BTagSF-like approaches that  don't use them.
But it's indeed the same approach we used for legacy and I agree with your UL changes.
I will merge this PR if there are no objections.

**Comment by TomasKello** [comment]
Ah I see, sorry for misunderstanding! I was advised to use MC efficiencies back then, I also have asked just recently on [CMS talk](https://cms-talk.web.cern.ch/t/pileup-jet-id-efficiency-scale-factors-for-ul/9029/4) if it is safe to use them so I hope it is fine.

**Comment by lviliani** [comment]
No problem at all, I was just confused because I couldn't remember we were using the same method for the legacy.

**Pull request merged**
