### PR TITLE
Scale sample

### PR DESCRIPTION
**Pull request by mlizzo**
mkDatacards.py has been updated in order to have the possibility to scale processes by a scale factor. One can now simply scale a given sample - and all related shape nuisances - by adding the 'scaleSample' key in the corresponding sample dictionary defined in structure.py. The value is the scale factor itself.

### CODE REVIEW

**Comment by lviliani** [comment]
I think you should remove all the commits except for 652b7cd

**Comment by amassiro** [comment]
Great idea @mlizzo !
May I suggest just a change in the name "scaleSample" into "scaleSampleForDatacard", just not to confuse people, since this scaling has no use by mkPlot.py (since the file structure.py is not used by mkPlot.py)?

**Comment by mlizzo** [comment]
Hi @lviliani, @amassiro, I should have removed non-related commits. I thought 'scaleSample' would have been enough since structure.py is not used by mkPlot as far as I know, it's only needed for datacards generation. Nevertheless I have updated the key's name to 'scaleSampleForDatacard', better avoid ambiguities :)

**Comment by lviliani** [comment]
I think it would be nice to add also the possibility to have different scale factors for different cuts.
Similar to what we do for plots:
https://github.com/latinos/LatinoAnalysis/blob/27e2a5b417b4a5b389172566e16df8fbe5a55927/ShapeAnalysis/python/PlotFactory.py#L267-L270

**Pull request merged**
