### PR TITLE
2016 VH EFT samples modified

### PR DESCRIPTION
**Pull request by sharmaaash**

### CODE REVIEW

**Comment by lviliani** [comment]
You have added nanoAODv5 datasets in the nanoAODv6 lists.
Please fix it using the correct datasets.

**Comment by sharmaaash** [comment]
> You have added nanoAODv5 datasets in the nanoAODv6 lists.
> Please fix it using the correct datasets.

From Xavier's request, these are declared in nanoAODv6 lists from nanoAODv5 dataset.(https://mattermost.web.cern.ch/latinos/channels/hww_ac).

**Comment by lviliani** [comment]
I don't think this is what @xjanssen meant.
If you want to have these samples in current trees production (v6 production), you need to edit the following lists:
**2016 nanoAODv5**: https://github.com/latinos/LatinoAnalysis/blob/master/NanoGardener/python/framework/samples/Summer16_102X_nAODv5.py
**2017 nanoAODv5**: https://github.com/latinos/LatinoAnalysis/blob/master/NanoGardener/python/framework/samples/fall17_102X_nAODv5.py
**2018 nanoAODv6**: https://github.com/latinos/LatinoAnalysis/blob/master/NanoGardener/python/framework/samples/Autumn18_102X_nAODv6.py
If instead you want the nanoAODv6 versions also for 2016 and 2017, those will be available in a future production.

**Comment by sharmaaash** [comment]
I have created another PR.

**Pull request closed without merging**
