### PR TITLE
Changes for Combined semileptonic skim

### PR DESCRIPTION
**Pull request by valsdav**
- Added Fatjet JER variations
- Added full FatJet JES regrouped variations to Combined semileptonic chain
- Preselections changes for VBSjjlnu jets

Some framework tweaks: 
- PostFitPlot scripts and DrawNuisances scripts should work with subsamples. 
- Added option in batchTools for automatic resubmitting in condor. 
To use it add AUTO_CONDOR_RETRY=True in your userConfig.py

### CODE REVIEW

**Comment by lenzip** [comment]
Hi, let me know when you think this is ready for merge

**Comment by valsdav** [comment]
Hi Lorenzo, I'm going to run some chains as a test and I'll let you know asap. 
If people from Semilep analysis want to check FatJet changes would be great!

I also added a module to include the boosted W tagging SF that should be general purpose

**Comment by valsdav** [comment]
I think this PR is ready to be merged :)

**Comment by uajanssen** [comment]
Ok, now it seems I can merge

**Pull request merged**
