### PR TITLE
Added cleaning step for FatJets

### PR DESCRIPTION
**Pull request by valsdav**
Hi!

I created a module to clean FatJet collection 
    1) kinematics cuts:  minpt, maxeta, max_tau21, mass_range
    2) for each FatJet passing the cuts the overlapping with leptons is checked
       with a configurable radius, (default 1.0)
    3) The CleanJet collection is checked to save a vector with the ids of the jets
        not overlapping with the CleanFatJet. (default radius 0.8)
The output of this module is a CleanFatJet collection with pt,eta,phi. Also a jetIdx reference to FatJet original collection is saved.
The list of CleanJet ids not overlapping with FatJets is saved in  CleanJetNotFat_jetIdx collection and relative size nCleanJetNotFat.

### CODE REVIEW

**Comment by soarnsoar** [comment]
Hi Davide :)

I have a question on dR between CleanFatJet and CleanJet. ( related to (3) )
As CleanJet has its cone size=0.4, if dR(Jet,FatJet) =0.8 there could be overlap between them.

So,  I am not sure that radius=0.8 between jet and fatjet is safe or not. I applied dR=1.2 before. (But it also seems too conservative).

Could you comment on this?


Best,

Junho

**Comment by valsdav** [comment]
Hi Juhno,
thanks for your comment. I agree indeed that 1.2 is safer and it should avoid any sharing of costituents between 0.4 and 0.8 jets. 
I have changed the default. 

Davide

**Comment by soarnsoar** [comment]
Hi Davide. Thanks for the reply!

Actually, I thinkdR=1.2 could be too large and I am not sure which value is appropriate yet. Anyway, we can set it to any value we want in the module. (I am considering setting dR to 1.0)

Thanks for the commit! I made my own module for fatjet before but didnt make a commit. it is almost the same with yours and yours is more flexible. 
This module looks fine.

**Comment by valsdav** [comment]
Thank Juhno, 
can we merge it?

**Pull request merged**
